In [1]:
import pandas  as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
import scipy.stats as personr

In [2]:
import pyodbc
print(pyodbc.drivers())

['SQL Server', 'ODBC Driver 18 for SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [3]:
import socket

try:
    s = socket.create_connection(("10.113.90.5", 1433), timeout=3)
    print( "SQL Server is reachable!")
except Exception as e:
    print("Connection failed:", e)

SQL Server is reachable!

* * This code creates a connection to the SQL Server database and reads the **Telco Customer Churn** table using an SQL query. 
The output is stored as a **Pandas DataFrame (`df`)** so that we can perform analysis and processing on the data.

In [4]:
import pandas as pd
from sqlalchemy import create_engine

username = 'ccna'
password = 'Hamed123'
server_ip = '10.113.90.5'
database = 'TelcoData'

conn_str = (
    f"mssql+pyodbc://{username}:{password}"
    f"@{server_ip}/{database}?driver=ODBC+Driver+18+for+SQL+Server&Encrypt=no"
)

engine = create_engine(conn_str)
# df = pd.read_sql("SELECT TOP 100 * FROM [WA_Fn-UseC_-Telco-Customer-Churn]", engine,)
df = pd.read_sql("SELECT * FROM [WA_Fn-UseC_-Telco-Customer-Churn]", engine,)
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.3,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.7,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.2,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.6,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.4,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No
7043,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn

In [5]:
query = "SELECT TOP 2 * FROM [WA_Fn-UseC_-Telco-Customer-Churn];"
df = pd.read_sql(query, engine)
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No

# Customer churn rate for each type of contract:

In [6]:
query = """
SELECT 
    Contract,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END)*100.0 / COUNT(*), 2) AS churn_rate_percent
FROM [WA_Fn-UseC_-Telco-Customer-Churn]
GROUP BY Contract;
"""
dfv = pd.read_sql_query(query, engine)
dfv

         Contract  total_customers  churned_customers  churn_rate_percent
0  Month-to-month             3875               1655               42.71
1        Two year             1695                 48                2.83
2        One year             1473                166               11.27
3        Contract                1                  0                0.00

# Calculating the drop rate with a pandas:
* * Calculating attrition rate with a spreadsheet If you have a large database, use a query, otherwise this method can also be used.

In [7]:
data = {
    'CustomerID': [1, 2, 3, 4, 5, 6, 7],
    'Contract': ['Monthly', 'One year', 'Monthly', 'Two year', 'Monthly', 'One year', 'Monthly'],
    'churn': ['Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes']
}

In [8]:
import pandas as pd
df1 = pd.DataFrame(data)
df1

   CustomerID  Contract churn
0           1   Monthly   Yes
1           2  One year    No
2           3   Monthly   Yes
3           4  Two year    No
4           5   Monthly    No
5           6  One year    No
6           7   Monthly   Yes

In [9]:
results = df1.groupby('Contract').agg(
    total_customers = ('Contract','count'),
    churned_customers = ('churn',lambda x: (x == 'Yes').sum())
)

results['Churn_rate_percent'] = (results['churned_customers'] / results ['total_customers'] * 100).round(2)

In [10]:
print(results.columns)

Index(['total_customers', 'churned_customers', 'Churn_rate_percent'], dtype='object')

In [11]:
results

          total_customers  churned_customers  Churn_rate_percent
Contract
Monthly                 4                  3                75.0
One year                2                  0                 0.0
Two year                1                  0                 0.0

In [12]:
query = """
SELECT Contract, COUNT(*) AS total_customers 
FROM dbo.[WA_Fn-UseC_-Telco-Customer-Churn]
GROUP BY Contract;
"""
dfm = pd.read_sql_query(query, engine)

In [13]:
dfm

         Contract  total_customers
0  Month-to-month             3875
1        Two year             1695
2        One year             1473
3        Contract                1

# This command uses the Inspector to display a list of tables in the specified schema (dbo):

In [14]:
from sqlalchemy import inspect

inspector = inspect(engine)
print(inspector.get_table_names(schema="dbo"))

['sysdiagrams', 'WA_Fn-UseC_-Telco-Customer-Churn']

# This loop traverses all schemas and prints the tables for each schema:

In [15]:
for schema in inspector.get_schema_names():
    print(schema, inspector.get_table_names(schema=schema))

db_accessadmin []
db_backupoperator []
db_datareader []
db_datawriter []
db_ddladmin []
db_denydatareader []
db_denydatawriter []
db_owner []
db_securityadmin []
dbo ['sysdiagrams', 'WA_Fn-UseC_-Telco-Customer-Churn']
guest []
INFORMATION_SCHEMA []
sys []

# It brings the list of tables and their schemas into the DataFrame with a direct SQL query:

In [16]:
dff = pd.read_sql("SELECT TABLE_SCHEMA, TABLE_NAME FROM INFORMATION_SCHEMA.TABLES;", engine)
print(dff)

  TABLE_SCHEMA                        TABLE_NAME
0          dbo  WA_Fn-UseC_-Telco-Customer-Churn
1          dbo                       sysdiagrams

In [17]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No

In [18]:
test_1= """
SELECT Contract, churn, COUNT(*) AS total_customers
FROM dbo.[WA_Fn-UseC_-Telco-Customer-Churn]
GROUP BY Contract, churn;
"""
df_1= pd.read_sql_query(test_1, engine)

In [19]:
df_1

         Contract  churn  total_customers
0        Contract  Churn                1
1        Two year     No             1647
2        Two year    Yes               48
3        One year     No             1307
4  Month-to-month    Yes             1655
5        One year    Yes              166
6  Month-to-month     No             2220

# Customer classification based on monthly amount

In [20]:
test_2 ="""
SELECT Contract,
       CASE 
         WHEN TRY_CAST(MonthlyCharges AS FLOAT) > 50 THEN 'High'
         WHEN TRY_CAST(MonthlyCharges AS FLOAT) BETWEEN 40 AND 50 THEN 'Medium'
         ELSE 'Low'
       END AS charge_category
FROM dbo.[WA_Fn-UseC_-Telco-Customer-Churn];
"""
df_2= pd.read_sql_query(test_2, engine)

In [21]:
df_2

            Contract charge_category
0     Month-to-month             Low
1           One year            High
2     Month-to-month            High
3           One year          Medium
4     Month-to-month            High
...              ...             ...
7039        One year            High
7040  Month-to-month             Low
7041  Month-to-month            High
7042        Two year            High
7043        Contract             Low

[7044 rows x 2 columns]

# Number of active and lapsed customers

In [22]:
test_3 ="""
SELECT 
    CASE WHEN Churn = 'Yes' THEN 'Churned' ELSE 'Active' END AS churn_status,
    COUNT(*) AS total_customers
FROM dbo.[WA_Fn-UseC_-Telco-Customer-Churn]
GROUP BY CASE WHEN Churn = 'Yes' THEN 'Churned' ELSE 'Active' END;
"""
df_3= pd.read_sql_query(test_3, engine)

In [23]:
df_3

  churn_status  total_customers
0       Active             5175
1      Churned             1869

- Cumulative total monthly cost by contract duration

In [24]:
test_4 ="""
SELECT customerID, MonthlyCharges,
       SUM (TRY_CAST(MonthlyCharges AS FLOAT)) OVER (ORDER BY tenure) AS running_total
FROM dbo.[WA_Fn-UseC_-Telco-Customer-Churn];
"""
df_4= pd.read_sql_query(test_4, engine)

In [25]:
df_4

      customerID  MonthlyCharges  running_total
0     4472-LVYGI           52.55          455.6
1     3115-CZMZD           20.25          455.6
2     5709-LVOEQ           80.85          455.6
3     4367-NUYAO           25.75          455.6
4     1371-DWPAZ           56.05          455.6
...          ...             ...            ...
7039  1750-CSKKM           55.35       456116.6
7040  3914-FDRHP           86.25       456116.6
7041  9547-ITEFG           102.6       456116.6
7042  8775-CEBBJ            44.2       456116.6
7043  customerID  MonthlyCharges       456116.6

[7044 rows x 3 columns]

- Average monthly cost for each contract type, next to each customer

In [26]:
test_5 ="""
SELECT Contract, customerID, MonthlyCharges,
       AVG(TRY_CAST(MonthlyCharges AS FLOAT)) OVER (PARTITION BY Contract) AS avg_charge_per_contract
FROM dbo.[WA_Fn-UseC_-Telco-Customer-Churn];
"""
df_5= pd.read_sql_query(test_5, engine)

In [27]:
df_5

            Contract  customerID  MonthlyCharges  avg_charge_per_contract
0           Contract  customerID  MonthlyCharges                      NaN
1     Month-to-month  4801-JZAZL            29.6                66.398490
2     Month-to-month  8361-LTMKD            74.4                66.398490
3     Month-to-month  6894-LFHLY           75.75                66.398490
4     Month-to-month  9767-FFLEM            69.5                66.398490
...              ...         ...             ...                      ...
7039        Two year  0264-CNITK            20.1                60.770413
7040        Two year  0440-EKDCF           60.15                60.770413
7041        Two year  4774-HHGGS           19.05                60.770413
7042        Two year  2272-WUSPA          110.75                60.770413
7043        Two year  4973-MGTON            84.4                60.770413

[7044 rows x 4 columns]

-  Groups customers by contract (GROUP BY)
- Calculates total number and number of dropped orders (CASE)
- Calculates percentage drop rate
- Ranks contracts by number of customers (OVER())

In [28]:
test_6 ="""
SELECT 
    Contract,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END)*100.0 / COUNT(*), 2) AS churn_rate_percent,
    RANK() OVER (ORDER BY COUNT(*) DESC) AS rank_by_contract_size
FROM dbo.[WA_Fn-UseC_-Telco-Customer-Churn]
GROUP BY Contract;
"""
df_6= pd.read_sql_query(test_6, engine)

In [29]:
df_6

,Contract,total_customers,churned_customers,churn_rate_percent,rank_by_contract_size
0,Month-to-month,3875,1655,42.71,1
1,Two year,1695,48,2.83,2
2,One year,1473,166,11.27,3
3,Contract,1,0,0.00,4